name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /workspaces/-zero-touch-helpdesk-

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full clone for version detection

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'pip'  # Enable caching for faster builds

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]  # Install in editable mode with dev dependencies
          pip install pytest slack_bolt python-dotenv psutil streamlit

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m pytest tests/ -v --cov=src --cov-report=xml

      - name: Verify imports
        run: |
          python -c "from src.automations.password_reset import generate_temp_password; print('✅ Import successful!')"

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: success()  # Only run if previous steps succeeded
